/*
  Baker 1031 — self-service info correction (/api/my-info), backed by Attio
  GET  ?cid=<personRecordId>&sig=<hmac>  → current values for the update form
  POST {cid, sig, ...fields}             → updates the Attio person (+ their open website deal)

  The link is personal: sig = HMAC-SHA256(recordId, SESSION_SECRET), generated by lead.mjs at
  submission time and stored on the person ("Update Link" attribute). No personal data travels in the URL.
*/
import crypto from 'node:crypto';
import { accreditedSignal, inviteVariant, buildInvite, sendViaResend, STATUS_FIELD } from './lib/invites.mjs';
import * as attio from './lib/attio.mjs';
import { tellCrm } from './lib/crm.mjs';
import { commissionValue, dealName, addDays, personPairs, dealPairs } from './lib/lead-shape.mjs';

const json = (status, body) => ({
  statusCode: status,
  headers: { 'content-type': 'application/json', 'cache-control': 'no-store' },
  body: JSON.stringify(body),
});

const sign = (cid) => crypto.createHmac('sha256', process.env.SESSION_SECRET || '').update('myinfo:' + cid).digest('hex').slice(0, 32);
function validSig(cid, sig) {
  if (!cid || !sig || !/^[A-Za-z0-9-]+$/.test(cid)) return false;
  const want = Buffer.from(sign(cid));
  const got = Buffer.from(String(sig));
  return want.length === got.length && crypto.timingSafeEqual(want, got);
}

// form key -> attribute title (person)
const PERSON_MAP = [
  ['role', 'Role (This Transaction)'], ['marital', 'Marital Status'], ['netWorth', 'Net Worth Range'],
  ['income', 'Household Income'], ['fit', 'Exchange Fit'],
  // previous form's extra fields, still shown by the update page when present
  ['familiarity', 'DST Familiarity'], ['reExperience', 'RE Experience'], ['riskComfort', 'Risk Comfort'],
  ['liquidityNeed', 'Liquidity Need'], ['horizon', 'Investment Horizon'], ['declineResponse', 'Decline Response'],
  ['ppExperience', 'Private Placement Experience'], ['assets', 'Asset Class Preferences'],
  ['regions', 'Region Preferences'], ['markets', 'Market Preferences'], ['features', 'Feature Interests'],
];
// form key -> attribute title (deal)
const DEAL_MAP = [
  ['saleDate', 'Sale Date'], ['equity', 'Exchange Equity'], ['debt', 'Replacement Debt'], ['fit', 'Exchange Fit'],
  ['objectives', 'Objectives'], ['amount', 'Cash Amount'], ['use', 'Primary Use'], ['cashHorizon', 'Cash Horizon'],
];
const bySlug = (attrs, title) => attrs.find((a) => a.title.toLowerCase() === title.toLowerCase());

export const handler = async (event) => {
  if (!attio.configured()) return json(500, { error: 'not configured' });

  const q = event.queryStringParameters || {};
  let body = {};
  if (event.httpMethod === 'POST') { try { body = JSON.parse(event.body || '{}'); } catch { return json(400, { error: 'bad json' }); } }
  const cid = event.httpMethod === 'GET' ? q.cid : body.cid;
  const sig = event.httpMethod === 'GET' ? q.sig : body.sig;
  if (!validSig(cid, sig)) return json(403, { error: 'invalid link' });

  let person;
  try { person = await attio.getPerson(cid); } catch (e) { return json(e.status === 404 ? 404 : 502, { error: e.status === 404 ? 'not found' : 'crm unavailable' }); }
  const flat = attio.flatValues(person);
  const pAttrs = await attio.attributes('people');
  const name = Array.isArray(flat.name) ? flat.name[0] : flat.name;

  if (event.httpMethod === 'GET') {
    const out = {
      firstName: name?.first_name || '', lastName: name?.last_name || '',
      email: Array.isArray(flat.email_addresses) ? flat.email_addresses[0] : flat.email_addresses || '',
      phone: Array.isArray(flat.phone_numbers) ? flat.phone_numbers[0] : flat.phone_numbers || '',
      state: '',
    };
    for (const [k, title] of PERSON_MAP) { const a = bySlug(pAttrs, title); if (a) out[k] = flat[a.slug] ?? null; }
    const deal = await attio.openDeal(cid);
    if (deal) {
      const dAttrs = await attio.attributes('deals');
      const df = attio.flatValues(deal);
      for (const [k, title] of DEAL_MAP) { const a = bySlug(dAttrs, title); if (a) out[k] = df[a.slug] ?? null; }
      out._dealId = deal.id.record_id;
    }
    for (const k of ['assets', 'regions', 'markets', 'features', 'objectives']) {
      if (typeof out[k] === 'string') out[k] = out[k] ? out[k].split(',').map((s) => s.trim()) : [];
      if (out[k] == null) out[k] = [];
    }
    return json(200, out);
  }

  if (event.httpMethod !== 'POST') return json(405, { error: 'GET or POST' });

  // ---- update the person ----
  const email = Array.isArray(flat.email_addresses) ? flat.email_addresses[0] : flat.email_addresses;
  const merged = { ...body, email: email || body.email };
  try {
    const values = {};
    if (body.firstName || body.lastName) {
      values.name = [{ first_name: body.firstName || name?.first_name || '', last_name: body.lastName || name?.last_name || '',
        full_name: [body.firstName || name?.first_name, body.lastName || name?.last_name].filter(Boolean).join(' ') }];
    }
    const phone = attio.e164(body.phone, body.phoneRegion);
    if (phone) values.phone_numbers = [{ original_phone_number: phone }];
    if (Object.keys(values).length) await attio.attio(`/objects/people/records/${cid}`, 'PATCH', { data: { values } });
  } catch (e) { console.error('[my-info] person update:', e.message); return json(502, { error: 'contact update failed' }); }
  const pairs = PERSON_MAP.filter(([k]) => k in body).map(([k, title]) => [title, body[k]]);
  // the role decides whether the accreditation screen applies; an update that does not resend it falls back to the stored one
  { const ra = bySlug(pAttrs, 'Role (This Transaction)'); if (merged.role == null && ra && flat[ra.slug]) merged.role = String(flat[ra.slug]); }
  pairs.push(['Accredited Signal', accreditedSignal(merged)]);
  await attio.setValues('people', cid, pairs);

  // ---- note the correction ----
  const changed = Object.keys(body).filter((k) => !['cid', 'sig'].includes(k));
  await attio.addNote('people', cid, 'Information updated via personal link',
    `Client updated their information via the self-service link (${new Date().toISOString().slice(0, 16)}Z).\n\nFields: ${changed.join(', ')}`, 'plaintext')
    .catch(() => {});

  // ---- tell the CRM, which moves its own copy of the closing date and the 45/180-day dates ----
  await tellCrm('site.info_updated', email, { saleDate: /^\d{4}-\d{2}-\d{2}$/.test(String(body.saleDate || '')) ? body.saleDate : '', ...(Number(body.equity) > 0 ? { equity: Number(body.equity) } : {}), ...(Number(body.debt) > 0 ? { debt: Number(body.debt) } : {}), fields: changed.slice(0, 20) },
    [body.firstName || name?.first_name, body.lastName || name?.last_name].filter(Boolean).join(' '));

  // ---- update the open deal ----
  const roleAttr = bySlug(pAttrs, 'Role (This Transaction)');
  const flatRole = roleAttr ? flat[roleAttr.slug] : undefined;
  try {
    const deal = await attio.openDeal(cid);
    if (deal) {
      await attio.updateDeal(deal.id.record_id, {
        name: ['firstName', 'lastName', 'role', 'path'].some((k) => k in body) ? dealName({ role: flatRole, ...merged, firstName: body.firstName || name?.first_name, lastName: body.lastName || name?.last_name }) : undefined,
        value: commissionValue(merged),
        pairs: [...DEAL_MAP.filter(([k]) => k in body).map(([k, title]) => [title, body[k]]),
          ...(body.saleDate ? [['45-Day Deadline', addDays(body.saleDate, 45)], ['180-Day Deadline', addDays(body.saleDate, 180)]] : [])],
      });
    }
  } catch (e) { console.error('[my-info] deal:', e.message); }

  // ---- keep the Airtable investor row's exchange dates in sync ----
  // (deadline reminders read Start Date / ID Period Expiration / 1031 Expiration from Airtable)
  if (body.saleDate && process.env.AIRTABLE_TOKEN && email) {
    try {
      const atBase = process.env.ACCESS_BASE_ID || 'appiKLSyAUmP0h8cJ';
      const atTable = process.env.ACCESS_TABLE_ID || 'tblbuFMpfv5R4DIyp';
      const formula = encodeURIComponent(`LOWER({Email Address}) = "${email.toLowerCase().replace(/"/g, '')}"`);
      const fr2 = await fetch(`https://api.airtable.com/v0/${atBase}/${atTable}?filterByFormula=${formula}&maxRecords=1`,
        { headers: { Authorization: `Bearer ${process.env.AIRTABLE_TOKEN}` } });
      const rec = fr2.ok ? ((await fr2.json()).records || [])[0] : null;
      if (rec) {
        await fetch(`https://api.airtable.com/v0/${atBase}/${atTable}/${rec.id}`, {
          method: 'PATCH',
          headers: { Authorization: `Bearer ${process.env.AIRTABLE_TOKEN}`, 'content-type': 'application/json' },
          body: JSON.stringify({ fields: {
            'Start Date': body.saleDate,
            'ID Period Expiration': addDays(body.saleDate, 45),
            '1031 Expiration': addDays(body.saleDate, 180),
          }, typecast: true }),
        });
      }
    } catch (e) { console.error('[my-info] airtable dates:', e.message); }
  }

  // Re-run qualification on the corrected data. A newly qualified lead gets the scheduling email —
  // unless one was already sent.
  let invited = false;
  try {
    const variant = inviteVariant(merged);
    if (variant) {
      const sf = bySlug(pAttrs, STATUS_FIELD);
      const status = sf ? String(flat[sf.slug] || '') : '';
      if (!status.startsWith('invited')) {
        const base = process.env.URL || 'https://baker1031.com';
        const msg = buildInvite(variant, body.firstName || name?.first_name || 'there', base);
        if (email && await sendViaResend(email, msg.subject, msg.html)) {
          invited = true;
          await attio.setValues('people', cid, [[STATUS_FIELD, `invited ${new Date().toISOString().slice(0, 16)}Z (${variant}, after update)`]]);
        }
      }
    }
  } catch (e) { console.error('[my-info] re-invite:', e.message); }

  return json(200, { ok: true, invited });
};
