/*
  Baker 1031 — self-service info correction (/api/my-info)
  GET  ?cid=<contactId>&sig=<hmac>  → current values for the update form
  POST {cid, sig, ...fields}        → updates the GHL contact (+ its open Leads opportunity)

  The link is personal: sig = HMAC-SHA256(contactId, SESSION_SECRET), generated by
  lead.mjs at submission time and stored on the contact ("Update Link" field). No
  personal data travels in the URL.
*/
import crypto from 'node:crypto';
import { accreditedSignal, inviteVariant, buildInvite, sendViaResend, hasAppointment, STATUS_FIELD } from './lib/invites.mjs';

const API = 'https://services.leadconnectorhq.com';
const json = (status, body) => ({
  statusCode: status,
  headers: { 'content-type': 'application/json', 'cache-control': 'no-store' },
  body: JSON.stringify(body),
});

const sign = (cid) => crypto.createHmac('sha256', process.env.SESSION_SECRET || '').update('myinfo:' + cid).digest('hex').slice(0, 32);
function validSig(cid, sig) {
  if (!cid || !sig || !/^[A-Za-z0-9]+$/.test(cid)) return false;
  const want = Buffer.from(sign(cid));
  const got = Buffer.from(String(sig));
  return want.length === got.length && crypto.timingSafeEqual(want, got);
}

// form payload key <-> GHL custom field name
const CONTACT_MAP = [
  ['role', 'Role (This Transaction)'],
  ['familiarity', 'DST Familiarity'],
  ['marital', 'Marital Status'],
  ['netWorth', 'Net Worth Range'],
  ['income', 'Household Income'],
  ['reExperience', 'RE Experience'],
  ['riskComfort', 'Risk Comfort'],
  ['liquidityNeed', 'Liquidity Need'],
  ['horizon', 'Investment Horizon'],
  ['declineResponse', 'Decline Response'],
  ['ppExperience', 'Private Placement Experience'],
  ['assets', 'Asset Class Preferences'],
  ['regions', 'Region Preferences'],
  ['markets', 'Market Preferences'],
  ['features', 'Feature Interests'],
];
const OPP_MAP = [
  ['saleDate', 'Sale Date'],
  ['equity', 'Exchange Equity'],
  ['debt', 'Replacement Debt'],
  ['fit', 'Exchange Fit'],
  ['objectives', 'Objectives'],
  ['amount', 'Cash Amount'],
  ['use', 'Primary Use'],
  ['cashHorizon', 'Cash Horizon'],
];

function addDays(iso, days) {
  const d = new Date(iso + 'T12:00:00Z');
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}
function commissionValue(lead) {
  const base = lead.path === 'exchange' ? lead.equity : lead.amount;
  return base ? Math.round(base * 0.9 * 0.05) : 0;
}
function dealType(lead) {
  if (lead.path !== 'exchange') return 'Cash';
  const objs = lead.objectives || [];
  return objs.includes('Planning a 1033 exchange') && !objs.includes('Planning a 1031 exchange') ? '1033' : '1031';
}
function opportunityName(lead) {
  const who = [lead.lastName, lead.firstName].filter(Boolean).join(', ') || lead.email;
  return [who, dealType(lead), lead.role || ''].filter(Boolean).join(' - ');
}

let fieldsCache = null; // [{id, name, model}]
async function loadFields(headers, loc) {
  if (fieldsCache) return fieldsCache;
  const r = await fetch(`${API}/locations/${loc}/customFields?model=all`, { headers });
  if (!r.ok) throw new Error(`fields ${r.status}`);
  fieldsCache = ((await r.json()).customFields || []).map((f) => ({ id: f.id, name: f.name, model: f.model || 'contact' }));
  return fieldsCache;
}
const byName = (fields, model, name) => fields.find((f) => f.model === model && f.name.toLowerCase() === name.toLowerCase());

async function openOpportunity(headers, loc, cid) {
  const r = await fetch(`${API}/opportunities/search?location_id=${loc}&contact_id=${cid}`, { headers });
  if (!r.ok) return null;
  const opps = (await r.json()).opportunities || [];
  return opps.filter((o) => o.status === 'open').sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))[0] || null;
}

export const handler = async (event) => {
  const key = process.env.GHL_Key || process.env.GHL_API_KEY;
  const loc = process.env.GHL_LOCATION_ID;
  if (!key || !loc) return json(500, { error: 'not configured' });
  const headers = { Authorization: `Bearer ${key}`, Version: '2021-07-28', 'content-type': 'application/json' };

  const q = event.queryStringParameters || {};
  let body = {};
  if (event.httpMethod === 'POST') { try { body = JSON.parse(event.body || '{}'); } catch { return json(400, { error: 'bad json' }); } }
  const cid = event.httpMethod === 'GET' ? q.cid : body.cid;
  const sig = event.httpMethod === 'GET' ? q.sig : body.sig;
  if (!validSig(cid, sig)) return json(403, { error: 'invalid link' });

  const fields = await loadFields(headers, loc);

  if (event.httpMethod === 'GET') {
    const r = await fetch(`${API}/contacts/${cid}`, { headers });
    if (!r.ok) return json(404, { error: 'not found' });
    const c = (await r.json()).contact || {};
    const cf = {};
    for (const v of c.customFields || []) cf[v.id] = v.value ?? v.field_value ?? v.fieldValue;
    const out = { firstName: c.firstName, lastName: c.lastName, email: c.email, phone: c.phone, state: c.state || '' };
    for (const [k, name] of CONTACT_MAP) { const f = byName(fields, 'contact', name); if (f) out[k] = cf[f.id] ?? null; }
    const opp = await openOpportunity(headers, loc, cid);
    if (opp) {
      const ocf = {};
      for (const v of opp.customFields || []) ocf[v.id] = v.value ?? v.field_value ?? v.fieldValue;
      for (const [k, name] of OPP_MAP) { const f = byName(fields, 'opportunity', name); if (f) out[k] = ocf[f.id] ?? null; }
      out._oppId = opp.id;
    }
    // normalize multi-selects to arrays
    for (const k of ['assets', 'regions', 'markets', 'features', 'objectives']) {
      if (typeof out[k] === 'string') out[k] = out[k] ? out[k].split(',').map((s) => s.trim()) : [];
    }
    return json(200, out);
  }

  if (event.httpMethod !== 'POST') return json(405, { error: 'GET or POST' });

  // ---- update contact ----
  const contactFields = [];
  for (const [k, name] of CONTACT_MAP) {
    if (!(k in body)) continue;
    const f = byName(fields, 'contact', name);
    if (f) contactFields.push({ id: f.id, field_value: body[k] });
  }
  const accField = byName(fields, 'contact', 'Accredited Signal');
  if (accField) contactFields.push({ id: accField.id, field_value: accreditedSignal(body) });
  const patch = { customFields: contactFields };
  for (const [k, gk] of [['firstName', 'firstName'], ['lastName', 'lastName'], ['phone', 'phone'], ['state', 'state']]) {
    if (body[k]) patch[gk] = body[k];
  }
  const ur = await fetch(`${API}/contacts/${cid}`, { method: 'PUT', headers, body: JSON.stringify(patch) });
  if (!ur.ok) return json(502, { error: 'contact update failed' });

  // ---- note the correction ----
  const changed = Object.keys(body).filter((k) => !['cid', 'sig'].includes(k));
  await fetch(`${API}/contacts/${cid}/notes`, {
    method: 'POST', headers,
    body: JSON.stringify({ body: `Client updated their information via the self-service link (${new Date().toISOString().slice(0, 16)}Z). Fields: ${changed.join(', ')}` }),
  }).catch(() => {});

  // ---- update the open opportunity ----
  try {
    const opp = await openOpportunity(headers, loc, cid);
    if (opp) {
      const oppFields = [];
      const pairs = [...OPP_MAP.map(([k, name]) => [name, body[k]]),
        ['45-Day Deadline', body.saleDate ? addDays(body.saleDate, 45) : undefined],
        ['180-Day Deadline', body.saleDate ? addDays(body.saleDate, 180) : undefined]];
      for (const [name, value] of pairs) {
        if (value === undefined) continue;
        const f = byName(fields, 'opportunity', name);
        if (f) oppFields.push({ id: f.id, field_value: value });
      }
      const upd = { customFields: oppFields, name: opportunityName(body), monetaryValue: commissionValue(body) };
      const or = await fetch(`${API}/opportunities/${opp.id}`, { method: 'PUT', headers, body: JSON.stringify(upd) });
      if (!or.ok) console.error('[my-info] opp update', or.status, (await or.text()).slice(0, 150));
    }
  } catch (e) { console.error('[my-info] opp:', e.message); }

  // ---- keep the Airtable investor row's exchange dates in sync ----
  // (deadline reminders read Start Date / ID Period Expiration / 1031
  //  Expiration from Airtable, so a changed sale date must land there too)
  if (body.saleDate && process.env.AIRTABLE_TOKEN) {
    try {
      const cr2 = await fetch(`${API}/contacts/${cid}`, { headers });
      const email = cr2.ok ? ((await cr2.json()).contact || {}).email : null;
      if (email) {
        const atBase = process.env.ACCESS_BASE_ID || 'appiKLSyAUmP0h8cJ';
        const atTable = process.env.ACCESS_TABLE_ID || 'tblbuFMpfv5R4DIyp';
        const formula = encodeURIComponent(`LOWER({Email Address}) = "${email.toLowerCase().replace(/"/g, '')}"`);
        const fr2 = await fetch(`https://api.airtable.com/v0/${atBase}/${atTable}?filterByFormula=${formula}&maxRecords=1`,
          { headers: { Authorization: `Bearer ${process.env.AIRTABLE_TOKEN}` } });
        const rec = fr2.ok ? ((await fr2.json()).records || [])[0] : null;
        if (rec) {
          await fetch(`https://api.airtable.com/v0/${atBase}/${atTable}/${rec.id}`, {
            method: 'PATCH',
            headers: { Authorization: `Bearer ${process.env.AIRTABLE_TOKEN}`, 'content-type': 'application/json' },
            body: JSON.stringify({ fields: {
              'Start Date': body.saleDate,
              'ID Period Expiration': addDays(body.saleDate, 45),
              '1031 Expiration': addDays(body.saleDate, 180),
            }, typecast: true }),
          });
        }
      }
    } catch (e) { console.error('[my-info] airtable dates:', e.message); }
  }

  // Re-run qualification on the corrected data. A newly qualified lead gets the
  // scheduling email — unless one was already sent, or a call is already booked.
  let invited = false;
  try {
    const variant = inviteVariant(body);
    if (variant) {
      const cr = await fetch(`${API}/contacts/${cid}`, { headers });
      const c = cr.ok ? (await cr.json()).contact || {} : {};
      const cf = {};
      for (const v of c.customFields || []) cf[v.id] = v.value ?? v.field_value ?? v.fieldValue;
      const sf = byName(fields, 'contact', STATUS_FIELD);
      const status = sf ? String(cf[sf.id] || '') : '';
      const alreadyInvited = status.startsWith('invited');
      const booked = await hasAppointment(headers, cid);
      if (!alreadyInvited && !booked) {
        const base = process.env.URL || 'https://baker1031.com';
        const msg = buildInvite(variant, body.firstName || c.firstName || 'there', base);
        if (await sendViaResend(c.email || body.email, msg.subject, msg.html)) {
          invited = true;
          if (sf) {
            await fetch(`${API}/contacts/${cid}`, {
              method: 'PUT', headers,
              body: JSON.stringify({ customFields: [{ id: sf.id, field_value: `invited ${new Date().toISOString().slice(0, 16)}Z (${variant}, after update)` }] }),
            }).catch(() => {});
          }
        }
      }
    }
  } catch (e) { console.error('[my-info] re-invite:', e.message); }

  return json(200, { ok: true, invited });
};
